/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user conversations
         * @description Retrieve all chat conversations for the currently authenticated user with pagination and sorting options
         */
        get: operations["getUserConversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Home page
         * @description Serves the home page of the API
         */
        get: operations["getRoot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Log in with email and password to get JWT token
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Log out the current user
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Get a new access token using a refresh token
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user account
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat with AI
         * @description Process chat request with OpenAI GPT 4 Omni model with web search capability
         */
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get chat history
         * @description Retrieve chat history for a user, either for all topics or for a specific topic
         */
        get: operations["getChatHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search-chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search chat history
         * @description Search in chat history for the currently authenticated user
         */
        get: operations["searchChatHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user profile
         * @description Get profile data for the currently logged-in user
         */
        get: operations["getUserProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Response schema for property listing description generator */
        PropertyListingResponse: {
            /** @description Catchy title for the property listing */
            title: string;
            /** @description Detailed description of the property */
            description: string;
            /** @description List of key features or highlights of the property */
            key_features: string[];
            /** @description Basic details about the property */
            property_details: {
                /** @description Property address */
                address: string;
                /** @description Number of bedrooms */
                beds?: number | string;
                /** @description Number of bathrooms */
                baths?: number | string;
                /** @description Type of property (apartment, house, condo, etc.) */
                property_type: string;
                /** @description Listing price of the property (optional) */
                price?: number | string;
                /** @description Square footage of the property (optional) */
                square_footage?: number | string;
            };
            /** @description Details about how the listing was generated */
            analysis_details: {
                /** @description Style of the listing description (professional, casual, luxury, etc.) */
                style_used?: string;
                /** @description Whether key highlights were included */
                included_highlights?: boolean;
                /** @description Whether neighborhood details were included */
                included_neighborhood?: boolean;
                /** @description Number of images analyzed */
                images_analyzed?: number;
            };
        };
        PointOfInterest: {
            /** @description Name of the point of interest */
            name?: string;
            /** @description Address of the point of interest */
            address?: string;
            /** @description Category of the point of interest */
            category?: string;
            /** @description Original category from API */
            original_category?: string;
            /** @description Distance in kilometers from the center location */
            distance_km?: number;
            geometry?: {
                location?: {
                    /** @description Latitude coordinate */
                    lat?: number;
                    /** @description Longitude coordinate */
                    lng?: number;
                };
            };
            /** @description User rating (if available) */
            rating?: number;
            /** @description Number of user ratings */
            user_ratings_total?: number;
            /** @description Google Places ID for the location */
            place_id?: string;
            /** @description URL to the Google Maps place */
            place_url?: string;
            /** @description URL to Google Maps marker location */
            map_marker_url?: string;
            /** @description URL to the icon for this place type */
            icon_url?: string;
            /** @description Website for the place (if available) */
            website?: string;
            /** @description Phone number for the place (if available) */
            phone?: string;
            /** @description Types of place from Google Places API */
            types?: string[];
            display_info?: {
                /** @description Display title for the place */
                title?: string;
                /** @description Display subtitle (usually address) */
                subtitle?: string;
                /** @description Human-readable category label */
                category_label?: string;
                /** @description Formatted rating text */
                rating_text?: string;
            };
            /** @description Relevance score for matching preferences */
            match_score?: number;
        };
        LifestyleMapResult: {
            /** @description Points of interest grouped by distance range */
            grouped_by_distance?: {
                /** @description Places within walking distance (0-1.5km) */
                walking_distance?: components["schemas"]["PointOfInterest"][];
                /** @description Places within biking distance (1.5-5km) */
                biking_distance?: components["schemas"]["PointOfInterest"][];
                /** @description Places within a short drive (5-10km) */
                short_drive?: components["schemas"]["PointOfInterest"][];
                /** @description Places further away (10-20km) */
                further_away?: components["schemas"]["PointOfInterest"][];
            };
            /** @description Information about the central location */
            location?: {
                /** @description Formatted address of the location */
                address?: string;
                /** @description Latitude coordinate */
                lat?: number;
                /** @description Longitude coordinate */
                lng?: number;
            };
            /** @description URL to Google Maps view of the location */
            map_url?: string;
            /** @description Points of interest grouped by category */
            points_of_interest?: {
                [key: string]: components["schemas"]["PointOfInterest"][];
            };
            /** @description Parameters used for the search */
            search_params?: Record<string, never>;
        };
        ExpenseCategory: {
            /** @description Name of the expense category */
            name?: string;
            /** @description Monthly amount for this category */
            amount?: number;
        };
        FamilyExpensesResult: {
            /** @description Location for the expense data (address, city, or neighborhood) */
            location?: string;
            /** @description Number of people in the family */
            family_size?: number;
            /** @description Currency code for the expense amounts */
            currency?: string;
            /** @description Detailed expense data */
            expense_data?: {
                /** @description Location for the expense data */
                location?: string;
                /** @description Number of people in the family */
                family_size?: number;
                /** @description Currency code for amounts */
                currency?: string;
                /** @description Total monthly expenses */
                total?: number;
                /** @description List of expense categories */
                categories?: components["schemas"]["ExpenseCategory"][];
                /** @description Additional context and explanation of the expense data */
                notes?: string;
            };
        };
        WebSearchResult: {
            /** @description Results from web search */
            search_results: {
                /** @description Title of the search result */
                title: string;
                /** @description URL of the search result */
                url: string;
                /** @description Snippet of text from the search result */
                snippet: string;
            }[];
        };
        ChatResponse: {
            /** @description The assistant's response message */
            message: string;
            /** @description List of tool calls made by the assistant */
            tool_calls?: {
                /** @description Unique identifier for the tool call */
                id: string;
                /**
                 * @description Type of tool call, currently only 'function' is supported
                 * @enum {string}
                 */
                type: "function";
                function: {
                    /** @description Name of the function to call */
                    name: string;
                    /** @description JSON string of arguments for the function */
                    arguments: string;
                };
            }[];
            /** @description Results of the tool calls */
            tool_results?: {
                /** @description ID of the tool call this result is for */
                tool_call_id: string;
                /** @description Name of the function that was called */
                function_name: string;
                /** @description Result object returned by the function with data specific to the function that was called */
                result: Record<string, never>;
            }[];
            /** @description Description of a map (if lifestyle map was requested) */
            map_description?: string;
            /** @description Filtered map data (if provided) */
            filtered_map_data?: {
                [key: string]: unknown;
            };
            /** @description Results from web search */
            web_search_results?: {
                /** @description Title of the search result */
                title: string;
                /** @description URL of the search result */
                url: string;
                /** @description Snippet of text from the search result */
                snippet: string;
            }[];
            /** @description Error message if something went wrong */
            error?: string;
        };
        SearchChatResponse: {
            /** @description The search query used */
            query?: string;
            /** @description List of matching conversations or messages */
            matches?: {
                /** @description Topic ID of the conversation */
                topic_id?: string;
                /** @description Title of the conversation (if available) */
                title?: string;
                /**
                 * @description Type of match: topic_or_title or content
                 * @enum {string}
                 */
                match_type?: "topic_or_title" | "content";
                /** @description ID of the message where content match was found (only for content matches) */
                message_id?: number;
                /** @description Preview of the matched content (only for content matches) */
                preview?: string;
                /**
                 * Format: date-time
                 * @description Creation timestamp
                 */
                created_at?: string;
                /**
                 * @description Role of the message sender (only for content matches)
                 * @enum {string}
                 */
                role?: "user" | "assistant" | "system" | "tool";
            }[];
        };
        UserProfileResponse: {
            user?: {
                /** @description User ID */
                id?: string;
                /** @description User email */
                email?: string;
                /** @description User's full name */
                name?: string;
                /** @description User role (admin, user, etc.) */
                role?: string;
                /**
                 * Format: date-time
                 * @description Account creation timestamp
                 */
                created_at?: string;
                /**
                 * Format: date-time
                 * @description Account last update timestamp
                 */
                updated_at?: string;
            };
            stats?: {
                /** @description Number of properties owned by the user */
                property_count?: number;
                /** @description Number of chat conversations for this user */
                conversation_count?: number;
            };
            /** @description List of properties owned by the user */
            properties?: {
                /** @description Property ID */
                id?: number;
                /** @description Property address */
                address?: string;
                /** @description Property city */
                city?: string;
                /** @description Property state */
                state?: string;
                /** @description Property ZIP code */
                zip_code?: string;
                /** @description Property price */
                price?: number;
                /** @description Number of bedrooms */
                beds?: number;
                /** @description Number of bathrooms */
                baths?: number;
                /** @description Square footage */
                sqft?: number;
                /** @description Type of property */
                property_type?: string;
                /** @description Year the property was built */
                year_built?: number;
            }[];
        };
        LoginRequest: {
            /**
             * Format: email
             * @description User email
             */
            email: string;
            /**
             * Format: password
             * @description User password
             */
            password: string;
        };
        LoginResponse: {
            success?: boolean;
            message?: string;
            user?: {
                id?: string;
                name?: string;
                email?: string;
                role?: string;
            };
            /** @description JWT access token */
            token?: string;
            /** @description JWT refresh token used to obtain new access tokens */
            refresh_token?: string;
            /** @description Token expiration time in seconds */
            expires_in?: number;
        };
        RefreshTokenRequest: {
            /** @description Refresh token obtained during login */
            refresh_token: string;
        };
        RefreshTokenResponse: {
            success?: boolean;
            message?: string;
            /** @description New JWT access token */
            token?: string;
            /** @description Token expiration time in seconds */
            expires_in?: number;
        };
        RegisterRequest: {
            /** @description User's full name */
            name: string;
            /**
             * Format: email
             * @description User email
             */
            email: string;
            /**
             * Format: password
             * @description User password (min 8 characters)
             */
            password: string;
        };
        RegisterResponse: {
            success?: boolean;
            message?: string;
            user?: {
                id?: string;
                name?: string;
                email?: string;
                role?: string;
            };
            token?: string;
        };
        ChatRequest: {
            /** @description External user ID to track conversation history */
            userId: string;
            /** @description Conversation topic ID to organize messages */
            topicId: string;
            /** @description User message content */
            message: string;
            /** @description Optional title for the conversation */
            title?: string;
            /**
             * Format: binary
             * @description Optional single image to analyze as part of the message
             */
            image?: string;
            /** @description Optional multiple images to analyze as part of the message (for property listings, etc.) */
            images?: string[];
        };
        ChatHistoryParams: {
            /** @description External user ID to get chat history for */
            userId: string;
            /** @description Optional topic ID to get history for a specific conversation */
            topicId?: string;
        };
        ChatHistorySingleTopicResponse: {
            /** @description Conversation topic ID */
            topic_id?: string;
            /** @description User ID */
            user_id?: string;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            created_at?: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at?: string;
            /** @description List of messages in this conversation */
            messages?: {
                /** @description Message role (user, assistant, system, tool) */
                role?: string;
                /** @description Message content */
                content?: string;
                /** @description Message sequence number */
                sequence?: number;
                /**
                 * Format: date-time
                 * @description Message timestamp
                 */
                timestamp?: string;
                /** @description Tool calls if any */
                tool_calls?: Record<string, never>;
                /** @description Tool results if any */
                tool_results?: Record<string, never>;
            }[];
        };
        UserConversationsResponse: {
            /** @description The ID of the authenticated user */
            user_id?: string;
            /** @description Total number of conversations available */
            total_count?: number;
            /** @description Maximum number of conversations returned in this response */
            limit?: number;
            /** @description Number of conversations skipped for pagination */
            offset?: number;
            /** @description List of conversations for the user */
            conversations?: {
                /** @description Unique database ID of the conversation */
                id?: string;
                /** @description Topic ID of the conversation */
                topic_id?: string;
                /** @description Title of the conversation (derived from content if not set) */
                title?: string;
                /** @description Number of messages in this conversation */
                message_count?: number;
                /** @description Preview text from the first user message */
                preview?: string;
                /**
                 * Format: date-time
                 * @description Creation timestamp
                 */
                created_at?: string;
                /**
                 * Format: date-time
                 * @description Last update timestamp
                 */
                updated_at?: string;
            }[];
        };
        ChatHistoryAllTopicsResponse: {
            /** @description User ID */
            user_id?: string;
            /** @description List of conversation topics */
            topics?: {
                /** @description Conversation topic ID */
                topic_id?: string;
                /** @description Optional conversation title */
                title?: string;
                /**
                 * Format: date-time
                 * @description Creation timestamp
                 */
                created_at?: string;
                /**
                 * Format: date-time
                 * @description Last update timestamp
                 */
                updated_at?: string;
                /** @description Number of messages in this conversation */
                message_count?: number;
                /** @description Preview of the last message */
                last_message?: string;
            }[];
        };
        ChatHistoryRequest: {
            /** @description External user ID */
            userId: string;
            /** @description Conversation topic ID */
            topicId: string;
            /**
             * @description Message role (user, assistant, system, tool)
             * @enum {string}
             */
            role: "user" | "assistant" | "system" | "tool";
            /** @description Message content */
            content: string;
            /** @description Optional JSON string of tool calls */
            tool_calls?: string;
            /** @description Optional JSON string of tool results */
            tool_results?: string;
            /** @description Optional JSON string of panel data for UI display */
            panel_data?: string;
        };
        SearchChatHistoryRequest: {
            /** @description Search query */
            query: string;
            /**
             * @description Maximum number of results to return
             * @default 10
             */
            limit: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getUserConversations: {
        parameters: {
            query?: {
                /** @description Maximum number of conversations to return (default: 50) */
                limit?: number;
                /** @description Number of conversations to skip (for pagination, default: 0) */
                offset?: number;
                /** @description Field to sort by (default: 'updated_at') */
                sort_by?: "created_at" | "updated_at" | "title";
                /** @description Sort order (default: 'desc') */
                sort_order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of conversations retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserConversationsResponse"];
                };
            };
            /** @description Unauthorized - Invalid or missing token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRoot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Home page served successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Login credentials */
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        message?: string;
                    };
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Refresh token request */
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Token refreshed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshTokenResponse"];
                };
            };
            /** @description Missing refresh token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Registration information */
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registration successful */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Invalid registration data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Chat request */
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ChatRequest"];
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Chat response generated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getChatHistory: {
        parameters: {
            query: {
                /** @description External user ID to get chat history for */
                userId: string;
                /** @description Optional topic ID to get history for a specific conversation */
                topicId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat history retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatHistorySingleTopicResponse"] | components["schemas"]["ChatHistoryAllTopicsResponse"];
                };
            };
            /** @description Missing required userId parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No conversation found for the specified topic */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    searchChatHistory: {
        parameters: {
            query: {
                /** @description Search query */
                query: string;
                /** @description Maximum number of results to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchChatResponse"];
                };
            };
            /** @description Missing required query parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
