/* tslint:disable */
/* eslint-disable */
/**
 * SARA AI Real Estate API
 * A sophisticated API for real estate intelligence
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ChatHistoryAllTopicsResponse
 */
export interface ChatHistoryAllTopicsResponse {
    /**
     * User ID
     * @type {string}
     * @memberof ChatHistoryAllTopicsResponse
     */
    'user_id'?: string;
    /**
     * List of conversation topics
     * @type {Array<ChatHistoryAllTopicsResponseTopicsInner>}
     * @memberof ChatHistoryAllTopicsResponse
     */
    'topics'?: Array<ChatHistoryAllTopicsResponseTopicsInner>;
}
/**
 * 
 * @export
 * @interface ChatHistoryAllTopicsResponseTopicsInner
 */
export interface ChatHistoryAllTopicsResponseTopicsInner {
    /**
     * Conversation topic ID
     * @type {string}
     * @memberof ChatHistoryAllTopicsResponseTopicsInner
     */
    'topic_id'?: string;
    /**
     * Optional conversation title
     * @type {string}
     * @memberof ChatHistoryAllTopicsResponseTopicsInner
     */
    'title'?: string;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof ChatHistoryAllTopicsResponseTopicsInner
     */
    'created_at'?: string;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof ChatHistoryAllTopicsResponseTopicsInner
     */
    'updated_at'?: string;
    /**
     * Number of messages in this conversation
     * @type {number}
     * @memberof ChatHistoryAllTopicsResponseTopicsInner
     */
    'message_count'?: number;
    /**
     * Preview of the last message
     * @type {string}
     * @memberof ChatHistoryAllTopicsResponseTopicsInner
     */
    'last_message'?: string;
}
/**
 * 
 * @export
 * @interface ChatHistoryParams
 */
export interface ChatHistoryParams {
    /**
     * External user ID to get chat history for
     * @type {string}
     * @memberof ChatHistoryParams
     */
    'userId': string;
    /**
     * Optional topic ID to get history for a specific conversation
     * @type {string}
     * @memberof ChatHistoryParams
     */
    'topicId'?: string;
}
/**
 * 
 * @export
 * @interface ChatHistoryRequest
 */
export interface ChatHistoryRequest {
    /**
     * External user ID
     * @type {string}
     * @memberof ChatHistoryRequest
     */
    'userId': string;
    /**
     * Conversation topic ID
     * @type {string}
     * @memberof ChatHistoryRequest
     */
    'topicId': string;
    /**
     * Message role (user, assistant, system, tool)
     * @type {string}
     * @memberof ChatHistoryRequest
     */
    'role': ChatHistoryRequestRoleEnum;
    /**
     * Message content
     * @type {string}
     * @memberof ChatHistoryRequest
     */
    'content': string;
    /**
     * Optional JSON string of tool calls
     * @type {string}
     * @memberof ChatHistoryRequest
     */
    'tool_calls'?: string;
    /**
     * Optional JSON string of tool results
     * @type {string}
     * @memberof ChatHistoryRequest
     */
    'tool_results'?: string;
    /**
     * Optional JSON string of panel data for UI display
     * @type {string}
     * @memberof ChatHistoryRequest
     */
    'panel_data'?: string;
}

export const ChatHistoryRequestRoleEnum = {
    User: 'user',
    Assistant: 'assistant',
    System: 'system',
    Tool: 'tool'
} as const;

export type ChatHistoryRequestRoleEnum = typeof ChatHistoryRequestRoleEnum[keyof typeof ChatHistoryRequestRoleEnum];

/**
 * 
 * @export
 * @interface ChatHistorySingleTopicResponse
 */
export interface ChatHistorySingleTopicResponse {
    /**
     * Conversation topic ID
     * @type {string}
     * @memberof ChatHistorySingleTopicResponse
     */
    'topic_id'?: string;
    /**
     * User ID
     * @type {string}
     * @memberof ChatHistorySingleTopicResponse
     */
    'user_id'?: string;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof ChatHistorySingleTopicResponse
     */
    'created_at'?: string;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof ChatHistorySingleTopicResponse
     */
    'updated_at'?: string;
    /**
     * List of messages in this conversation
     * @type {Array<ChatHistorySingleTopicResponseMessagesInner>}
     * @memberof ChatHistorySingleTopicResponse
     */
    'messages'?: Array<ChatHistorySingleTopicResponseMessagesInner>;
}
/**
 * 
 * @export
 * @interface ChatHistorySingleTopicResponseMessagesInner
 */
export interface ChatHistorySingleTopicResponseMessagesInner {
    /**
     * Message role (user, assistant, system, tool)
     * @type {string}
     * @memberof ChatHistorySingleTopicResponseMessagesInner
     */
    'role'?: string;
    /**
     * Message content
     * @type {string}
     * @memberof ChatHistorySingleTopicResponseMessagesInner
     */
    'content'?: string;
    /**
     * Message sequence number
     * @type {number}
     * @memberof ChatHistorySingleTopicResponseMessagesInner
     */
    'sequence'?: number;
    /**
     * Message timestamp
     * @type {string}
     * @memberof ChatHistorySingleTopicResponseMessagesInner
     */
    'timestamp'?: string;
    /**
     * Tool calls if any
     * @type {object}
     * @memberof ChatHistorySingleTopicResponseMessagesInner
     */
    'tool_calls'?: object;
    /**
     * Tool results if any
     * @type {object}
     * @memberof ChatHistorySingleTopicResponseMessagesInner
     */
    'tool_results'?: object;
}
/**
 * 
 * @export
 * @interface ChatRequest
 */
export interface ChatRequest {
    /**
     * External user ID to track conversation history
     * @type {string}
     * @memberof ChatRequest
     */
    'userId': string;
    /**
     * Conversation topic ID to organize messages
     * @type {string}
     * @memberof ChatRequest
     */
    'topicId': string;
    /**
     * User message content
     * @type {string}
     * @memberof ChatRequest
     */
    'message': string;
    /**
     * Optional title for the conversation
     * @type {string}
     * @memberof ChatRequest
     */
    'title'?: string;
    /**
     * Optional single image to analyze as part of the message
     * @type {File}
     * @memberof ChatRequest
     */
    'image'?: File;
    /**
     * Optional multiple images to analyze as part of the message (for property listings, etc.)
     * @type {Array<File>}
     * @memberof ChatRequest
     */
    'images'?: Array<File>;
}
/**
 * 
 * @export
 * @interface ChatResponse
 */
export interface ChatResponse {
    /**
     * The assistant\'s response message
     * @type {string}
     * @memberof ChatResponse
     */
    'message': string;
    /**
     * List of tool calls made by the assistant
     * @type {Array<ChatResponseToolCallsInner>}
     * @memberof ChatResponse
     */
    'tool_calls'?: Array<ChatResponseToolCallsInner>;
    /**
     * Results of the tool calls
     * @type {Array<ChatResponseToolResultsInner>}
     * @memberof ChatResponse
     */
    'tool_results'?: Array<ChatResponseToolResultsInner>;
    /**
     * Description of a map (if lifestyle map was requested)
     * @type {string}
     * @memberof ChatResponse
     */
    'map_description'?: string;
    /**
     * Filtered map data (if provided)
     * @type {{ [key: string]: any; }}
     * @memberof ChatResponse
     */
    'filtered_map_data'?: { [key: string]: any; };
    /**
     * Results from web search
     * @type {Array<WebSearchResultSearchResultsInner>}
     * @memberof ChatResponse
     */
    'web_search_results'?: Array<WebSearchResultSearchResultsInner>;
    /**
     * Error message if something went wrong
     * @type {string}
     * @memberof ChatResponse
     */
    'error'?: string;
}
/**
 * 
 * @export
 * @interface ChatResponseToolCallsInner
 */
export interface ChatResponseToolCallsInner {
    /**
     * Unique identifier for the tool call
     * @type {string}
     * @memberof ChatResponseToolCallsInner
     */
    'id': string;
    /**
     * Type of tool call, currently only \'function\' is supported
     * @type {string}
     * @memberof ChatResponseToolCallsInner
     */
    'type': ChatResponseToolCallsInnerTypeEnum;
    /**
     * 
     * @type {ChatResponseToolCallsInnerFunction}
     * @memberof ChatResponseToolCallsInner
     */
    'function': ChatResponseToolCallsInnerFunction;
}

export const ChatResponseToolCallsInnerTypeEnum = {
    Function: 'function'
} as const;

export type ChatResponseToolCallsInnerTypeEnum = typeof ChatResponseToolCallsInnerTypeEnum[keyof typeof ChatResponseToolCallsInnerTypeEnum];

/**
 * 
 * @export
 * @interface ChatResponseToolCallsInnerFunction
 */
export interface ChatResponseToolCallsInnerFunction {
    /**
     * Name of the function to call
     * @type {string}
     * @memberof ChatResponseToolCallsInnerFunction
     */
    'name': string;
    /**
     * JSON string of arguments for the function
     * @type {string}
     * @memberof ChatResponseToolCallsInnerFunction
     */
    'arguments': string;
}
/**
 * 
 * @export
 * @interface ChatResponseToolResultsInner
 */
export interface ChatResponseToolResultsInner {
    /**
     * ID of the tool call this result is for
     * @type {string}
     * @memberof ChatResponseToolResultsInner
     */
    'tool_call_id': string;
    /**
     * Name of the function that was called
     * @type {string}
     * @memberof ChatResponseToolResultsInner
     */
    'function_name': string;
    /**
     * Result object returned by the function with data specific to the function that was called
     * @type {object}
     * @memberof ChatResponseToolResultsInner
     */
    'result': object;
}
/**
 * 
 * @export
 * @interface ExpenseCategory
 */
export interface ExpenseCategory {
    /**
     * Name of the expense category
     * @type {string}
     * @memberof ExpenseCategory
     */
    'name'?: string;
    /**
     * Monthly amount for this category
     * @type {number}
     * @memberof ExpenseCategory
     */
    'amount'?: number;
}
/**
 * 
 * @export
 * @interface FamilyExpensesResult
 */
export interface FamilyExpensesResult {
    /**
     * Location for the expense data (address, city, or neighborhood)
     * @type {string}
     * @memberof FamilyExpensesResult
     */
    'location'?: string;
    /**
     * Number of people in the family
     * @type {number}
     * @memberof FamilyExpensesResult
     */
    'family_size'?: number;
    /**
     * Currency code for the expense amounts
     * @type {string}
     * @memberof FamilyExpensesResult
     */
    'currency'?: string;
    /**
     * 
     * @type {FamilyExpensesResultExpenseData}
     * @memberof FamilyExpensesResult
     */
    'expense_data'?: FamilyExpensesResultExpenseData;
}
/**
 * Detailed expense data
 * @export
 * @interface FamilyExpensesResultExpenseData
 */
export interface FamilyExpensesResultExpenseData {
    /**
     * Location for the expense data
     * @type {string}
     * @memberof FamilyExpensesResultExpenseData
     */
    'location'?: string;
    /**
     * Number of people in the family
     * @type {number}
     * @memberof FamilyExpensesResultExpenseData
     */
    'family_size'?: number;
    /**
     * Currency code for amounts
     * @type {string}
     * @memberof FamilyExpensesResultExpenseData
     */
    'currency'?: string;
    /**
     * Total monthly expenses
     * @type {number}
     * @memberof FamilyExpensesResultExpenseData
     */
    'total'?: number;
    /**
     * List of expense categories
     * @type {Array<ExpenseCategory>}
     * @memberof FamilyExpensesResultExpenseData
     */
    'categories'?: Array<ExpenseCategory>;
    /**
     * Additional context and explanation of the expense data
     * @type {string}
     * @memberof FamilyExpensesResultExpenseData
     */
    'notes'?: string;
}
/**
 * @type GetChatHistory200Response
 * @export
 */
export type GetChatHistory200Response = ChatHistoryAllTopicsResponse | ChatHistorySingleTopicResponse;

/**
 * 
 * @export
 * @interface LifestyleMapResult
 */
export interface LifestyleMapResult {
    /**
     * 
     * @type {LifestyleMapResultGroupedByDistance}
     * @memberof LifestyleMapResult
     */
    'grouped_by_distance'?: LifestyleMapResultGroupedByDistance;
    /**
     * 
     * @type {LifestyleMapResultLocation}
     * @memberof LifestyleMapResult
     */
    'location'?: LifestyleMapResultLocation;
    /**
     * URL to Google Maps view of the location
     * @type {string}
     * @memberof LifestyleMapResult
     */
    'map_url'?: string;
    /**
     * Points of interest grouped by category
     * @type {{ [key: string]: Array<PointOfInterest>; }}
     * @memberof LifestyleMapResult
     */
    'points_of_interest'?: { [key: string]: Array<PointOfInterest>; };
    /**
     * Parameters used for the search
     * @type {object}
     * @memberof LifestyleMapResult
     */
    'search_params'?: object;
}
/**
 * Points of interest grouped by distance range
 * @export
 * @interface LifestyleMapResultGroupedByDistance
 */
export interface LifestyleMapResultGroupedByDistance {
    /**
     * Places within walking distance (0-1.5km)
     * @type {Array<PointOfInterest>}
     * @memberof LifestyleMapResultGroupedByDistance
     */
    'walking_distance'?: Array<PointOfInterest>;
    /**
     * Places within biking distance (1.5-5km)
     * @type {Array<PointOfInterest>}
     * @memberof LifestyleMapResultGroupedByDistance
     */
    'biking_distance'?: Array<PointOfInterest>;
    /**
     * Places within a short drive (5-10km)
     * @type {Array<PointOfInterest>}
     * @memberof LifestyleMapResultGroupedByDistance
     */
    'short_drive'?: Array<PointOfInterest>;
    /**
     * Places further away (10-20km)
     * @type {Array<PointOfInterest>}
     * @memberof LifestyleMapResultGroupedByDistance
     */
    'further_away'?: Array<PointOfInterest>;
}
/**
 * Information about the central location
 * @export
 * @interface LifestyleMapResultLocation
 */
export interface LifestyleMapResultLocation {
    /**
     * Formatted address of the location
     * @type {string}
     * @memberof LifestyleMapResultLocation
     */
    'address'?: string;
    /**
     * Latitude coordinate
     * @type {number}
     * @memberof LifestyleMapResultLocation
     */
    'lat'?: number;
    /**
     * Longitude coordinate
     * @type {number}
     * @memberof LifestyleMapResultLocation
     */
    'lng'?: number;
}
/**
 * 
 * @export
 * @interface LoginRequest
 */
export interface LoginRequest {
    /**
     * User email
     * @type {string}
     * @memberof LoginRequest
     */
    'email': string;
    /**
     * User password
     * @type {string}
     * @memberof LoginRequest
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
    /**
     * 
     * @type {boolean}
     * @memberof LoginResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    'message'?: string;
    /**
     * 
     * @type {LoginResponseUser}
     * @memberof LoginResponse
     */
    'user'?: LoginResponseUser;
    /**
     * JWT access token
     * @type {string}
     * @memberof LoginResponse
     */
    'token'?: string;
    /**
     * JWT refresh token used to obtain new access tokens
     * @type {string}
     * @memberof LoginResponse
     */
    'refresh_token'?: string;
    /**
     * Token expiration time in seconds
     * @type {number}
     * @memberof LoginResponse
     */
    'expires_in'?: number;
}
/**
 * 
 * @export
 * @interface LoginResponseUser
 */
export interface LoginResponseUser {
    /**
     * 
     * @type {string}
     * @memberof LoginResponseUser
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponseUser
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponseUser
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponseUser
     */
    'role'?: string;
}
/**
 * 
 * @export
 * @interface Logout200Response
 */
export interface Logout200Response {
    /**
     * 
     * @type {boolean}
     * @memberof Logout200Response
     */
    'success'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Logout200Response
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface PointOfInterest
 */
export interface PointOfInterest {
    /**
     * Name of the point of interest
     * @type {string}
     * @memberof PointOfInterest
     */
    'name'?: string;
    /**
     * Address of the point of interest
     * @type {string}
     * @memberof PointOfInterest
     */
    'address'?: string;
    /**
     * Category of the point of interest
     * @type {string}
     * @memberof PointOfInterest
     */
    'category'?: string;
    /**
     * Original category from API
     * @type {string}
     * @memberof PointOfInterest
     */
    'original_category'?: string;
    /**
     * Distance in kilometers from the center location
     * @type {number}
     * @memberof PointOfInterest
     */
    'distance_km'?: number;
    /**
     * 
     * @type {PointOfInterestGeometry}
     * @memberof PointOfInterest
     */
    'geometry'?: PointOfInterestGeometry;
    /**
     * User rating (if available)
     * @type {number}
     * @memberof PointOfInterest
     */
    'rating'?: number;
    /**
     * Number of user ratings
     * @type {number}
     * @memberof PointOfInterest
     */
    'user_ratings_total'?: number;
    /**
     * Google Places ID for the location
     * @type {string}
     * @memberof PointOfInterest
     */
    'place_id'?: string;
    /**
     * URL to the Google Maps place
     * @type {string}
     * @memberof PointOfInterest
     */
    'place_url'?: string;
    /**
     * URL to Google Maps marker location
     * @type {string}
     * @memberof PointOfInterest
     */
    'map_marker_url'?: string;
    /**
     * URL to the icon for this place type
     * @type {string}
     * @memberof PointOfInterest
     */
    'icon_url'?: string;
    /**
     * Website for the place (if available)
     * @type {string}
     * @memberof PointOfInterest
     */
    'website'?: string;
    /**
     * Phone number for the place (if available)
     * @type {string}
     * @memberof PointOfInterest
     */
    'phone'?: string;
    /**
     * Types of place from Google Places API
     * @type {Array<string>}
     * @memberof PointOfInterest
     */
    'types'?: Array<string>;
    /**
     * 
     * @type {PointOfInterestDisplayInfo}
     * @memberof PointOfInterest
     */
    'display_info'?: PointOfInterestDisplayInfo;
    /**
     * Relevance score for matching preferences
     * @type {number}
     * @memberof PointOfInterest
     */
    'match_score'?: number;
}
/**
 * 
 * @export
 * @interface PointOfInterestDisplayInfo
 */
export interface PointOfInterestDisplayInfo {
    /**
     * Display title for the place
     * @type {string}
     * @memberof PointOfInterestDisplayInfo
     */
    'title'?: string;
    /**
     * Display subtitle (usually address)
     * @type {string}
     * @memberof PointOfInterestDisplayInfo
     */
    'subtitle'?: string;
    /**
     * Human-readable category label
     * @type {string}
     * @memberof PointOfInterestDisplayInfo
     */
    'category_label'?: string;
    /**
     * Formatted rating text
     * @type {string}
     * @memberof PointOfInterestDisplayInfo
     */
    'rating_text'?: string;
}
/**
 * 
 * @export
 * @interface PointOfInterestGeometry
 */
export interface PointOfInterestGeometry {
    /**
     * 
     * @type {PointOfInterestGeometryLocation}
     * @memberof PointOfInterestGeometry
     */
    'location'?: PointOfInterestGeometryLocation;
}
/**
 * 
 * @export
 * @interface PointOfInterestGeometryLocation
 */
export interface PointOfInterestGeometryLocation {
    /**
     * Latitude coordinate
     * @type {number}
     * @memberof PointOfInterestGeometryLocation
     */
    'lat'?: number;
    /**
     * Longitude coordinate
     * @type {number}
     * @memberof PointOfInterestGeometryLocation
     */
    'lng'?: number;
}
/**
 * Response schema for property listing description generator
 * @export
 * @interface PropertyListingResponse
 */
export interface PropertyListingResponse {
    /**
     * Catchy title for the property listing
     * @type {string}
     * @memberof PropertyListingResponse
     */
    'title': string;
    /**
     * Detailed description of the property
     * @type {string}
     * @memberof PropertyListingResponse
     */
    'description': string;
    /**
     * List of key features or highlights of the property
     * @type {Array<string>}
     * @memberof PropertyListingResponse
     */
    'key_features': Array<string>;
    /**
     * 
     * @type {PropertyListingResponsePropertyDetails}
     * @memberof PropertyListingResponse
     */
    'property_details': PropertyListingResponsePropertyDetails;
    /**
     * 
     * @type {PropertyListingResponseAnalysisDetails}
     * @memberof PropertyListingResponse
     */
    'analysis_details': PropertyListingResponseAnalysisDetails;
}
/**
 * Details about how the listing was generated
 * @export
 * @interface PropertyListingResponseAnalysisDetails
 */
export interface PropertyListingResponseAnalysisDetails {
    /**
     * Style of the listing description (professional, casual, luxury, etc.)
     * @type {string}
     * @memberof PropertyListingResponseAnalysisDetails
     */
    'style_used'?: string;
    /**
     * Whether key highlights were included
     * @type {boolean}
     * @memberof PropertyListingResponseAnalysisDetails
     */
    'included_highlights'?: boolean;
    /**
     * Whether neighborhood details were included
     * @type {boolean}
     * @memberof PropertyListingResponseAnalysisDetails
     */
    'included_neighborhood'?: boolean;
    /**
     * Number of images analyzed
     * @type {number}
     * @memberof PropertyListingResponseAnalysisDetails
     */
    'images_analyzed'?: number;
}
/**
 * Basic details about the property
 * @export
 * @interface PropertyListingResponsePropertyDetails
 */
export interface PropertyListingResponsePropertyDetails {
    /**
     * Property address
     * @type {string}
     * @memberof PropertyListingResponsePropertyDetails
     */
    'address': string;
    /**
     * Number of bedrooms
     * @type {any}
     * @memberof PropertyListingResponsePropertyDetails
     */
    'beds'?: any;
    /**
     * Number of bathrooms
     * @type {any}
     * @memberof PropertyListingResponsePropertyDetails
     */
    'baths'?: any;
    /**
     * Type of property (apartment, house, condo, etc.)
     * @type {string}
     * @memberof PropertyListingResponsePropertyDetails
     */
    'property_type': string;
    /**
     * Listing price of the property (optional)
     * @type {any}
     * @memberof PropertyListingResponsePropertyDetails
     */
    'price'?: any;
    /**
     * Square footage of the property (optional)
     * @type {any}
     * @memberof PropertyListingResponsePropertyDetails
     */
    'square_footage'?: any;
}
/**
 * 
 * @export
 * @interface RefreshTokenRequest
 */
export interface RefreshTokenRequest {
    /**
     * Refresh token obtained during login
     * @type {string}
     * @memberof RefreshTokenRequest
     */
    'refresh_token': string;
}
/**
 * 
 * @export
 * @interface RefreshTokenResponse
 */
export interface RefreshTokenResponse {
    /**
     * 
     * @type {boolean}
     * @memberof RefreshTokenResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RefreshTokenResponse
     */
    'message'?: string;
    /**
     * New JWT access token
     * @type {string}
     * @memberof RefreshTokenResponse
     */
    'token'?: string;
    /**
     * Token expiration time in seconds
     * @type {number}
     * @memberof RefreshTokenResponse
     */
    'expires_in'?: number;
}
/**
 * 
 * @export
 * @interface RegisterRequest
 */
export interface RegisterRequest {
    /**
     * User\'s full name
     * @type {string}
     * @memberof RegisterRequest
     */
    'name': string;
    /**
     * User email
     * @type {string}
     * @memberof RegisterRequest
     */
    'email': string;
    /**
     * User password (min 8 characters)
     * @type {string}
     * @memberof RegisterRequest
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface RegisterResponse
 */
export interface RegisterResponse {
    /**
     * 
     * @type {boolean}
     * @memberof RegisterResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RegisterResponse
     */
    'message'?: string;
    /**
     * 
     * @type {LoginResponseUser}
     * @memberof RegisterResponse
     */
    'user'?: LoginResponseUser;
    /**
     * 
     * @type {string}
     * @memberof RegisterResponse
     */
    'token'?: string;
}
/**
 * 
 * @export
 * @interface SearchChatHistoryRequest
 */
export interface SearchChatHistoryRequest {
    /**
     * Search query
     * @type {string}
     * @memberof SearchChatHistoryRequest
     */
    'query': string;
    /**
     * Maximum number of results to return
     * @type {number}
     * @memberof SearchChatHistoryRequest
     */
    'limit'?: number;
}
/**
 * 
 * @export
 * @interface SearchChatResponse
 */
export interface SearchChatResponse {
    /**
     * The search query used
     * @type {string}
     * @memberof SearchChatResponse
     */
    'query'?: string;
    /**
     * List of matching conversations or messages
     * @type {Array<SearchChatResponseMatchesInner>}
     * @memberof SearchChatResponse
     */
    'matches'?: Array<SearchChatResponseMatchesInner>;
}
/**
 * 
 * @export
 * @interface SearchChatResponseMatchesInner
 */
export interface SearchChatResponseMatchesInner {
    /**
     * Topic ID of the conversation
     * @type {string}
     * @memberof SearchChatResponseMatchesInner
     */
    'topic_id'?: string;
    /**
     * Title of the conversation (if available)
     * @type {string}
     * @memberof SearchChatResponseMatchesInner
     */
    'title'?: string;
    /**
     * Type of match: topic_or_title or content
     * @type {string}
     * @memberof SearchChatResponseMatchesInner
     */
    'match_type'?: SearchChatResponseMatchesInnerMatchTypeEnum;
    /**
     * ID of the message where content match was found (only for content matches)
     * @type {number}
     * @memberof SearchChatResponseMatchesInner
     */
    'message_id'?: number;
    /**
     * Preview of the matched content (only for content matches)
     * @type {string}
     * @memberof SearchChatResponseMatchesInner
     */
    'preview'?: string;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof SearchChatResponseMatchesInner
     */
    'created_at'?: string;
    /**
     * Role of the message sender (only for content matches)
     * @type {string}
     * @memberof SearchChatResponseMatchesInner
     */
    'role'?: SearchChatResponseMatchesInnerRoleEnum;
}

export const SearchChatResponseMatchesInnerMatchTypeEnum = {
    TopicOrTitle: 'topic_or_title',
    Content: 'content'
} as const;

export type SearchChatResponseMatchesInnerMatchTypeEnum = typeof SearchChatResponseMatchesInnerMatchTypeEnum[keyof typeof SearchChatResponseMatchesInnerMatchTypeEnum];
export const SearchChatResponseMatchesInnerRoleEnum = {
    User: 'user',
    Assistant: 'assistant',
    System: 'system',
    Tool: 'tool'
} as const;

export type SearchChatResponseMatchesInnerRoleEnum = typeof SearchChatResponseMatchesInnerRoleEnum[keyof typeof SearchChatResponseMatchesInnerRoleEnum];

/**
 * 
 * @export
 * @interface UserConversationsResponse
 */
export interface UserConversationsResponse {
    /**
     * The ID of the authenticated user
     * @type {string}
     * @memberof UserConversationsResponse
     */
    'user_id'?: string;
    /**
     * Total number of conversations available
     * @type {number}
     * @memberof UserConversationsResponse
     */
    'total_count'?: number;
    /**
     * Maximum number of conversations returned in this response
     * @type {number}
     * @memberof UserConversationsResponse
     */
    'limit'?: number;
    /**
     * Number of conversations skipped for pagination
     * @type {number}
     * @memberof UserConversationsResponse
     */
    'offset'?: number;
    /**
     * List of conversations for the user
     * @type {Array<UserConversationsResponseConversationsInner>}
     * @memberof UserConversationsResponse
     */
    'conversations'?: Array<UserConversationsResponseConversationsInner>;
}
/**
 * 
 * @export
 * @interface UserConversationsResponseConversationsInner
 */
export interface UserConversationsResponseConversationsInner {
    /**
     * Unique database ID of the conversation
     * @type {string}
     * @memberof UserConversationsResponseConversationsInner
     */
    'id'?: string;
    /**
     * Topic ID of the conversation
     * @type {string}
     * @memberof UserConversationsResponseConversationsInner
     */
    'topic_id'?: string;
    /**
     * Title of the conversation (derived from content if not set)
     * @type {string}
     * @memberof UserConversationsResponseConversationsInner
     */
    'title'?: string;
    /**
     * Number of messages in this conversation
     * @type {number}
     * @memberof UserConversationsResponseConversationsInner
     */
    'message_count'?: number;
    /**
     * Preview text from the first user message
     * @type {string}
     * @memberof UserConversationsResponseConversationsInner
     */
    'preview'?: string;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof UserConversationsResponseConversationsInner
     */
    'created_at'?: string;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof UserConversationsResponseConversationsInner
     */
    'updated_at'?: string;
}
/**
 * 
 * @export
 * @interface UserProfileResponse
 */
export interface UserProfileResponse {
    /**
     * 
     * @type {UserProfileResponseUser}
     * @memberof UserProfileResponse
     */
    'user'?: UserProfileResponseUser;
    /**
     * 
     * @type {UserProfileResponseStats}
     * @memberof UserProfileResponse
     */
    'stats'?: UserProfileResponseStats;
    /**
     * List of properties owned by the user
     * @type {Array<UserProfileResponsePropertiesInner>}
     * @memberof UserProfileResponse
     */
    'properties'?: Array<UserProfileResponsePropertiesInner>;
}
/**
 * 
 * @export
 * @interface UserProfileResponsePropertiesInner
 */
export interface UserProfileResponsePropertiesInner {
    /**
     * Property ID
     * @type {number}
     * @memberof UserProfileResponsePropertiesInner
     */
    'id'?: number;
    /**
     * Property address
     * @type {string}
     * @memberof UserProfileResponsePropertiesInner
     */
    'address'?: string;
    /**
     * Property city
     * @type {string}
     * @memberof UserProfileResponsePropertiesInner
     */
    'city'?: string;
    /**
     * Property state
     * @type {string}
     * @memberof UserProfileResponsePropertiesInner
     */
    'state'?: string;
    /**
     * Property ZIP code
     * @type {string}
     * @memberof UserProfileResponsePropertiesInner
     */
    'zip_code'?: string;
    /**
     * Property price
     * @type {number}
     * @memberof UserProfileResponsePropertiesInner
     */
    'price'?: number;
    /**
     * Number of bedrooms
     * @type {number}
     * @memberof UserProfileResponsePropertiesInner
     */
    'beds'?: number;
    /**
     * Number of bathrooms
     * @type {number}
     * @memberof UserProfileResponsePropertiesInner
     */
    'baths'?: number;
    /**
     * Square footage
     * @type {number}
     * @memberof UserProfileResponsePropertiesInner
     */
    'sqft'?: number;
    /**
     * Type of property
     * @type {string}
     * @memberof UserProfileResponsePropertiesInner
     */
    'property_type'?: string;
    /**
     * Year the property was built
     * @type {number}
     * @memberof UserProfileResponsePropertiesInner
     */
    'year_built'?: number;
}
/**
 * 
 * @export
 * @interface UserProfileResponseStats
 */
export interface UserProfileResponseStats {
    /**
     * Number of properties owned by the user
     * @type {number}
     * @memberof UserProfileResponseStats
     */
    'property_count'?: number;
    /**
     * Number of chat conversations for this user
     * @type {number}
     * @memberof UserProfileResponseStats
     */
    'conversation_count'?: number;
}
/**
 * 
 * @export
 * @interface UserProfileResponseUser
 */
export interface UserProfileResponseUser {
    /**
     * User ID
     * @type {string}
     * @memberof UserProfileResponseUser
     */
    'id'?: string;
    /**
     * User email
     * @type {string}
     * @memberof UserProfileResponseUser
     */
    'email'?: string;
    /**
     * User\'s full name
     * @type {string}
     * @memberof UserProfileResponseUser
     */
    'name'?: string;
    /**
     * User role (admin, user, etc.)
     * @type {string}
     * @memberof UserProfileResponseUser
     */
    'role'?: string;
    /**
     * Account creation timestamp
     * @type {string}
     * @memberof UserProfileResponseUser
     */
    'created_at'?: string;
    /**
     * Account last update timestamp
     * @type {string}
     * @memberof UserProfileResponseUser
     */
    'updated_at'?: string;
}
/**
 * 
 * @export
 * @interface WebSearchResult
 */
export interface WebSearchResult {
    /**
     * Results from web search
     * @type {Array<WebSearchResultSearchResultsInner>}
     * @memberof WebSearchResult
     */
    'search_results': Array<WebSearchResultSearchResultsInner>;
}
/**
 * 
 * @export
 * @interface WebSearchResultSearchResultsInner
 */
export interface WebSearchResultSearchResultsInner {
    /**
     * Title of the search result
     * @type {string}
     * @memberof WebSearchResultSearchResultsInner
     */
    'title': string;
    /**
     * URL of the search result
     * @type {string}
     * @memberof WebSearchResultSearchResultsInner
     */
    'url': string;
    /**
     * Snippet of text from the search result
     * @type {string}
     * @memberof WebSearchResultSearchResultsInner
     */
    'snippet': string;
}

/**
 * AuthenticationApi - axios parameter creator
 * @export
 */
export const AuthenticationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Log in with email and password to get JWT token
         * @summary Login
         * @param {LoginRequest} loginRequest Login credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (loginRequest: LoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginRequest' is not null or undefined
            assertParamExists('login', 'loginRequest', loginRequest)
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Log out the current user
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a new access token using a refresh token
         * @summary Refresh Token
         * @param {RefreshTokenRequest} refreshTokenRequest Refresh token request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refreshToken: async (refreshTokenRequest: RefreshTokenRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'refreshTokenRequest' is not null or undefined
            assertParamExists('refreshToken', 'refreshTokenRequest', refreshTokenRequest)
            const localVarPath = `/auth/refresh`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(refreshTokenRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Register a new user account
         * @summary Register
         * @param {RegisterRequest} registerRequest Registration information
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        register: async (registerRequest: RegisterRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'registerRequest' is not null or undefined
            assertParamExists('register', 'registerRequest', registerRequest)
            const localVarPath = `/auth/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthenticationApi - functional programming interface
 * @export
 */
export const AuthenticationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthenticationApiAxiosParamCreator(configuration)
    return {
        /**
         * Log in with email and password to get JWT token
         * @summary Login
         * @param {LoginRequest} loginRequest Login credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(loginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.login']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Log out the current user
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logout(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Logout200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logout(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.logout']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get a new access token using a refresh token
         * @summary Refresh Token
         * @param {RefreshTokenRequest} refreshTokenRequest Refresh token request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async refreshToken(refreshTokenRequest: RefreshTokenRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RefreshTokenResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.refreshToken(refreshTokenRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.refreshToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Register a new user account
         * @summary Register
         * @param {RegisterRequest} registerRequest Registration information
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async register(registerRequest: RegisterRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RegisterResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.register(registerRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.register']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthenticationApi - factory interface
 * @export
 */
export const AuthenticationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthenticationApiFp(configuration)
    return {
        /**
         * Log in with email and password to get JWT token
         * @summary Login
         * @param {LoginRequest} loginRequest Login credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<LoginResponse> {
            return localVarFp.login(loginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Log out the current user
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout(options?: RawAxiosRequestConfig): AxiosPromise<Logout200Response> {
            return localVarFp.logout(options).then((request) => request(axios, basePath));
        },
        /**
         * Get a new access token using a refresh token
         * @summary Refresh Token
         * @param {RefreshTokenRequest} refreshTokenRequest Refresh token request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refreshToken(refreshTokenRequest: RefreshTokenRequest, options?: RawAxiosRequestConfig): AxiosPromise<RefreshTokenResponse> {
            return localVarFp.refreshToken(refreshTokenRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Register a new user account
         * @summary Register
         * @param {RegisterRequest} registerRequest Registration information
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        register(registerRequest: RegisterRequest, options?: RawAxiosRequestConfig): AxiosPromise<RegisterResponse> {
            return localVarFp.register(registerRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthenticationApi - object-oriented interface
 * @export
 * @class AuthenticationApi
 * @extends {BaseAPI}
 */
export class AuthenticationApi extends BaseAPI {
    /**
     * Log in with email and password to get JWT token
     * @summary Login
     * @param {LoginRequest} loginRequest Login credentials
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).login(loginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Log out the current user
     * @summary Logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public logout(options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).logout(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get a new access token using a refresh token
     * @summary Refresh Token
     * @param {RefreshTokenRequest} refreshTokenRequest Refresh token request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public refreshToken(refreshTokenRequest: RefreshTokenRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).refreshToken(refreshTokenRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Register a new user account
     * @summary Register
     * @param {RegisterRequest} registerRequest Registration information
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public register(registerRequest: RegisterRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).register(registerRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * FeaturesApi - axios parameter creator
 * @export
 */
export const FeaturesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Process chat request with OpenAI GPT 4 Omni model with web search capability
         * @summary Chat with AI
         * @param {string} userId External user ID to track conversation history
         * @param {string} topicId Conversation topic ID to organize messages
         * @param {string} message User message content
         * @param {string} [title] Optional title for the conversation
         * @param {File} [image] Optional single image to analyze as part of the message
         * @param {Array<File>} [images] Optional multiple images to analyze as part of the message (for property listings, etc.)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chat: async (userId: string, topicId: string, message: string, title?: string, image?: File, images?: Array<File>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('chat', 'userId', userId)
            // verify required parameter 'topicId' is not null or undefined
            assertParamExists('chat', 'topicId', topicId)
            // verify required parameter 'message' is not null or undefined
            assertParamExists('chat', 'message', message)
            const localVarPath = `/chat`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            if (userId !== undefined) { 
                localVarFormParams.append('userId', userId as any);
            }
    
            if (topicId !== undefined) { 
                localVarFormParams.append('topicId', topicId as any);
            }
    
            if (message !== undefined) { 
                localVarFormParams.append('message', message as any);
            }
    
            if (title !== undefined) { 
                localVarFormParams.append('title', title as any);
            }
    
            if (image !== undefined) { 
                localVarFormParams.append('image', image as any);
            }
                if (images) {
                images.forEach((element) => {
                    localVarFormParams.append('images', element as any);
                })
            }

    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve chat history for a user, either for all topics or for a specific topic
         * @summary Get chat history
         * @param {string} userId External user ID to get chat history for
         * @param {string} [topicId] Optional topic ID to get history for a specific conversation
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getChatHistory: async (userId: string, topicId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getChatHistory', 'userId', userId)
            const localVarPath = `/chat-history`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }

            if (topicId !== undefined) {
                localVarQueryParameter['topicId'] = topicId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve all chat conversations for the currently authenticated user with pagination and sorting options
         * @summary Get user conversations
         * @param {number} [limit] Maximum number of conversations to return (default: 50)
         * @param {number} [offset] Number of conversations to skip (for pagination, default: 0)
         * @param {GetUserConversationsSortByEnum} [sortBy] Field to sort by (default: \&#39;updated_at\&#39;)
         * @param {GetUserConversationsSortOrderEnum} [sortOrder] Sort order (default: \&#39;desc\&#39;)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserConversations: async (limit?: number, offset?: number, sortBy?: GetUserConversationsSortByEnum, sortOrder?: GetUserConversationsSortOrderEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/conversations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sort_by'] = sortBy;
            }

            if (sortOrder !== undefined) {
                localVarQueryParameter['sort_order'] = sortOrder;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Search in chat history for the currently authenticated user
         * @summary Search chat history
         * @param {string} query Search query
         * @param {number} [limit] Maximum number of results to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchChatHistory: async (query: string, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'query' is not null or undefined
            assertParamExists('searchChatHistory', 'query', query)
            const localVarPath = `/search-chat`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (query !== undefined) {
                localVarQueryParameter['query'] = query;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FeaturesApi - functional programming interface
 * @export
 */
export const FeaturesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FeaturesApiAxiosParamCreator(configuration)
    return {
        /**
         * Process chat request with OpenAI GPT 4 Omni model with web search capability
         * @summary Chat with AI
         * @param {string} userId External user ID to track conversation history
         * @param {string} topicId Conversation topic ID to organize messages
         * @param {string} message User message content
         * @param {string} [title] Optional title for the conversation
         * @param {File} [image] Optional single image to analyze as part of the message
         * @param {Array<File>} [images] Optional multiple images to analyze as part of the message (for property listings, etc.)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async chat(userId: string, topicId: string, message: string, title?: string, image?: File, images?: Array<File>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ChatResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.chat(userId, topicId, message, title, image, images, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FeaturesApi.chat']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve chat history for a user, either for all topics or for a specific topic
         * @summary Get chat history
         * @param {string} userId External user ID to get chat history for
         * @param {string} [topicId] Optional topic ID to get history for a specific conversation
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getChatHistory(userId: string, topicId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetChatHistory200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getChatHistory(userId, topicId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FeaturesApi.getChatHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve all chat conversations for the currently authenticated user with pagination and sorting options
         * @summary Get user conversations
         * @param {number} [limit] Maximum number of conversations to return (default: 50)
         * @param {number} [offset] Number of conversations to skip (for pagination, default: 0)
         * @param {GetUserConversationsSortByEnum} [sortBy] Field to sort by (default: \&#39;updated_at\&#39;)
         * @param {GetUserConversationsSortOrderEnum} [sortOrder] Sort order (default: \&#39;desc\&#39;)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserConversations(limit?: number, offset?: number, sortBy?: GetUserConversationsSortByEnum, sortOrder?: GetUserConversationsSortOrderEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserConversationsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserConversations(limit, offset, sortBy, sortOrder, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FeaturesApi.getUserConversations']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Search in chat history for the currently authenticated user
         * @summary Search chat history
         * @param {string} query Search query
         * @param {number} [limit] Maximum number of results to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchChatHistory(query: string, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SearchChatResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchChatHistory(query, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FeaturesApi.searchChatHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FeaturesApi - factory interface
 * @export
 */
export const FeaturesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FeaturesApiFp(configuration)
    return {
        /**
         * Process chat request with OpenAI GPT 4 Omni model with web search capability
         * @summary Chat with AI
         * @param {string} userId External user ID to track conversation history
         * @param {string} topicId Conversation topic ID to organize messages
         * @param {string} message User message content
         * @param {string} [title] Optional title for the conversation
         * @param {File} [image] Optional single image to analyze as part of the message
         * @param {Array<File>} [images] Optional multiple images to analyze as part of the message (for property listings, etc.)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chat(userId: string, topicId: string, message: string, title?: string, image?: File, images?: Array<File>, options?: RawAxiosRequestConfig): AxiosPromise<ChatResponse> {
            return localVarFp.chat(userId, topicId, message, title, image, images, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve chat history for a user, either for all topics or for a specific topic
         * @summary Get chat history
         * @param {string} userId External user ID to get chat history for
         * @param {string} [topicId] Optional topic ID to get history for a specific conversation
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getChatHistory(userId: string, topicId?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetChatHistory200Response> {
            return localVarFp.getChatHistory(userId, topicId, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve all chat conversations for the currently authenticated user with pagination and sorting options
         * @summary Get user conversations
         * @param {number} [limit] Maximum number of conversations to return (default: 50)
         * @param {number} [offset] Number of conversations to skip (for pagination, default: 0)
         * @param {GetUserConversationsSortByEnum} [sortBy] Field to sort by (default: \&#39;updated_at\&#39;)
         * @param {GetUserConversationsSortOrderEnum} [sortOrder] Sort order (default: \&#39;desc\&#39;)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserConversations(limit?: number, offset?: number, sortBy?: GetUserConversationsSortByEnum, sortOrder?: GetUserConversationsSortOrderEnum, options?: RawAxiosRequestConfig): AxiosPromise<UserConversationsResponse> {
            return localVarFp.getUserConversations(limit, offset, sortBy, sortOrder, options).then((request) => request(axios, basePath));
        },
        /**
         * Search in chat history for the currently authenticated user
         * @summary Search chat history
         * @param {string} query Search query
         * @param {number} [limit] Maximum number of results to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchChatHistory(query: string, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<SearchChatResponse> {
            return localVarFp.searchChatHistory(query, limit, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FeaturesApi - object-oriented interface
 * @export
 * @class FeaturesApi
 * @extends {BaseAPI}
 */
export class FeaturesApi extends BaseAPI {
    /**
     * Process chat request with OpenAI GPT 4 Omni model with web search capability
     * @summary Chat with AI
     * @param {string} userId External user ID to track conversation history
     * @param {string} topicId Conversation topic ID to organize messages
     * @param {string} message User message content
     * @param {string} [title] Optional title for the conversation
     * @param {File} [image] Optional single image to analyze as part of the message
     * @param {Array<File>} [images] Optional multiple images to analyze as part of the message (for property listings, etc.)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeaturesApi
     */
    public chat(userId: string, topicId: string, message: string, title?: string, image?: File, images?: Array<File>, options?: RawAxiosRequestConfig) {
        return FeaturesApiFp(this.configuration).chat(userId, topicId, message, title, image, images, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve chat history for a user, either for all topics or for a specific topic
     * @summary Get chat history
     * @param {string} userId External user ID to get chat history for
     * @param {string} [topicId] Optional topic ID to get history for a specific conversation
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeaturesApi
     */
    public getChatHistory(userId: string, topicId?: string, options?: RawAxiosRequestConfig) {
        return FeaturesApiFp(this.configuration).getChatHistory(userId, topicId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve all chat conversations for the currently authenticated user with pagination and sorting options
     * @summary Get user conversations
     * @param {number} [limit] Maximum number of conversations to return (default: 50)
     * @param {number} [offset] Number of conversations to skip (for pagination, default: 0)
     * @param {GetUserConversationsSortByEnum} [sortBy] Field to sort by (default: \&#39;updated_at\&#39;)
     * @param {GetUserConversationsSortOrderEnum} [sortOrder] Sort order (default: \&#39;desc\&#39;)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeaturesApi
     */
    public getUserConversations(limit?: number, offset?: number, sortBy?: GetUserConversationsSortByEnum, sortOrder?: GetUserConversationsSortOrderEnum, options?: RawAxiosRequestConfig) {
        return FeaturesApiFp(this.configuration).getUserConversations(limit, offset, sortBy, sortOrder, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Search in chat history for the currently authenticated user
     * @summary Search chat history
     * @param {string} query Search query
     * @param {number} [limit] Maximum number of results to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeaturesApi
     */
    public searchChatHistory(query: string, limit?: number, options?: RawAxiosRequestConfig) {
        return FeaturesApiFp(this.configuration).searchChatHistory(query, limit, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const GetUserConversationsSortByEnum = {
    CreatedAt: 'created_at',
    UpdatedAt: 'updated_at',
    Title: 'title'
} as const;
export type GetUserConversationsSortByEnum = typeof GetUserConversationsSortByEnum[keyof typeof GetUserConversationsSortByEnum];
/**
 * @export
 */
export const GetUserConversationsSortOrderEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type GetUserConversationsSortOrderEnum = typeof GetUserConversationsSortOrderEnum[keyof typeof GetUserConversationsSortOrderEnum];


/**
 * GeneralApi - axios parameter creator
 * @export
 */
export const GeneralApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Serves the home page of the API
         * @summary Home page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRoot: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GeneralApi - functional programming interface
 * @export
 */
export const GeneralApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GeneralApiAxiosParamCreator(configuration)
    return {
        /**
         * Serves the home page of the API
         * @summary Home page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRoot(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRoot(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GeneralApi.getRoot']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GeneralApi - factory interface
 * @export
 */
export const GeneralApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GeneralApiFp(configuration)
    return {
        /**
         * Serves the home page of the API
         * @summary Home page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRoot(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getRoot(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GeneralApi - object-oriented interface
 * @export
 * @class GeneralApi
 * @extends {BaseAPI}
 */
export class GeneralApi extends BaseAPI {
    /**
     * Serves the home page of the API
     * @summary Home page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GeneralApi
     */
    public getRoot(options?: RawAxiosRequestConfig) {
        return GeneralApiFp(this.configuration).getRoot(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get profile data for the currently logged-in user
         * @summary Get user profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserProfile: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/profile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * Get profile data for the currently logged-in user
         * @summary Get user profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserProfile(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserProfileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserProfile(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getUserProfile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * Get profile data for the currently logged-in user
         * @summary Get user profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserProfile(options?: RawAxiosRequestConfig): AxiosPromise<UserProfileResponse> {
            return localVarFp.getUserProfile(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI {
    /**
     * Get profile data for the currently logged-in user
     * @summary Get user profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public getUserProfile(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getUserProfile(options).then((request) => request(this.axios, this.basePath));
    }
}



