/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
import * as reactQuery from "@tanstack/react-query";
import { useSaraContext, SaraContext, queryKeyFn } from "./saraContext";
import { deepMerge } from "./saraUtils";
import type * as Fetcher from "./saraFetcher";
import { saraFetch } from "./saraFetcher";
import type * as Schemas from "./saraSchemas";

type QueryFnOptions = {
  signal?: AbortController["signal"];
};

export type GetUserConversationsQueryParams = {
  /**
   * Maximum number of conversations to return (default: 50)
   *
   * @default 50
   */
  limit?: number;
  /**
   * Number of conversations to skip (for pagination, default: 0)
   *
   * @default 0
   */
  offset?: number;
  /**
   * Field to sort by (default: 'updated_at')
   *
   * @default updated_at
   */
  sort_by?: "created_at" | "updated_at" | "title";
  /**
   * Sort order (default: 'desc')
   *
   * @default desc
   */
  sort_order?: "asc" | "desc";
};

export type GetUserConversationsError = Fetcher.ErrorWrapper<undefined>;

export type GetUserConversationsVariables = {
  queryParams?: GetUserConversationsQueryParams;
} & SaraContext["fetcherOptions"];

/**
 * Retrieve all chat conversations for the currently authenticated user with pagination and sorting options
 */
export const fetchGetUserConversations = (
  variables: GetUserConversationsVariables,
  signal?: AbortSignal
) =>
  saraFetch<
    Schemas.UserConversationsResponse,
    GetUserConversationsError,
    undefined,
    {},
    GetUserConversationsQueryParams,
    {}
  >({ url: "/conversations", method: "get", ...variables, signal });

/**
 * Retrieve all chat conversations for the currently authenticated user with pagination and sorting options
 */
export function getUserConversationsQuery(
  variables: GetUserConversationsVariables
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (
    options: QueryFnOptions
  ) => Promise<Schemas.UserConversationsResponse>;
};

export function getUserConversationsQuery(
  variables: GetUserConversationsVariables | reactQuery.SkipToken
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.UserConversationsResponse>)
    | reactQuery.SkipToken;
};

export function getUserConversationsQuery(
  variables: GetUserConversationsVariables | reactQuery.SkipToken
) {
  return {
    queryKey: queryKeyFn({
      path: "/conversations",
      operationId: "getUserConversations",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchGetUserConversations(variables, signal),
  };
}

/**
 * Retrieve all chat conversations for the currently authenticated user with pagination and sorting options
 */
export const useSuspenseGetUserConversations = <
  TData = Schemas.UserConversationsResponse,
>(
  variables: GetUserConversationsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.UserConversationsResponse,
      GetUserConversationsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >
) => {
  const { queryOptions, fetcherOptions } = useSaraContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.UserConversationsResponse,
    GetUserConversationsError,
    TData
  >({
    ...getUserConversationsQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

/**
 * Retrieve all chat conversations for the currently authenticated user with pagination and sorting options
 */
export const useGetUserConversations = <
  TData = Schemas.UserConversationsResponse,
>(
  variables: GetUserConversationsVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.UserConversationsResponse,
      GetUserConversationsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >
) => {
  const { queryOptions, fetcherOptions } = useSaraContext(options);
  return reactQuery.useQuery<
    Schemas.UserConversationsResponse,
    GetUserConversationsError,
    TData
  >({
    ...getUserConversationsQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables)
    ),
    ...options,
    ...queryOptions,
  });
};

export type GetRootError = Fetcher.ErrorWrapper<undefined>;

export type GetRootVariables = SaraContext["fetcherOptions"];

/**
 * Serves the home page of the API
 */
export const fetchGetRoot = (
  variables: GetRootVariables,
  signal?: AbortSignal
) =>
  saraFetch<undefined, GetRootError, undefined, {}, {}, {}>({
    url: "/",
    method: "get",
    ...variables,
    signal,
  });

/**
 * Serves the home page of the API
 */
export function getRootQuery(variables: GetRootVariables): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<undefined>;
};

export function getRootQuery(
  variables: GetRootVariables | reactQuery.SkipToken
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<undefined>)
    | reactQuery.SkipToken;
};

export function getRootQuery(
  variables: GetRootVariables | reactQuery.SkipToken
) {
  return {
    queryKey: queryKeyFn({
      path: "/",
      operationId: "getRoot",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) => fetchGetRoot(variables, signal),
  };
}

/**
 * Serves the home page of the API
 */
export const useSuspenseGetRoot = <TData = undefined>(
  variables: GetRootVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<undefined, GetRootError, TData>,
    "queryKey" | "queryFn" | "initialData"
  >
) => {
  const { queryOptions, fetcherOptions } = useSaraContext(options);
  return reactQuery.useSuspenseQuery<undefined, GetRootError, TData>({
    ...getRootQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

/**
 * Serves the home page of the API
 */
export const useGetRoot = <TData = undefined>(
  variables: GetRootVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<undefined, GetRootError, TData>,
    "queryKey" | "queryFn" | "initialData"
  >
) => {
  const { queryOptions, fetcherOptions } = useSaraContext(options);
  return reactQuery.useQuery<undefined, GetRootError, TData>({
    ...getRootQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables)
    ),
    ...options,
    ...queryOptions,
  });
};

export type LoginError = Fetcher.ErrorWrapper<undefined>;

export type LoginVariables = {
  body: Schemas.LoginRequest;
} & SaraContext["fetcherOptions"];

/**
 * Log in with email and password to get JWT token
 */
export const fetchLogin = (variables: LoginVariables, signal?: AbortSignal) =>
  saraFetch<
    Schemas.LoginResponse,
    LoginError,
    Schemas.LoginRequest,
    {},
    {},
    {}
  >({ url: "/auth/login", method: "post", ...variables, signal });

/**
 * Log in with email and password to get JWT token
 */
export const useLogin = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.LoginResponse,
      LoginError,
      LoginVariables
    >,
    "mutationFn"
  >
) => {
  const { fetcherOptions } = useSaraContext();
  return reactQuery.useMutation<
    Schemas.LoginResponse,
    LoginError,
    LoginVariables
  >({
    mutationFn: (variables: LoginVariables) =>
      fetchLogin(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type LogoutError = Fetcher.ErrorWrapper<undefined>;

export type LogoutResponse = {
  success?: boolean;
  message?: string;
};

export type LogoutVariables = SaraContext["fetcherOptions"];

/**
 * Log out the current user
 */
export const fetchLogout = (variables: LogoutVariables, signal?: AbortSignal) =>
  saraFetch<LogoutResponse, LogoutError, undefined, {}, {}, {}>({
    url: "/auth/logout",
    method: "post",
    ...variables,
    signal,
  });

/**
 * Log out the current user
 */
export const useLogout = (
  options?: Omit<
    reactQuery.UseMutationOptions<LogoutResponse, LogoutError, LogoutVariables>,
    "mutationFn"
  >
) => {
  const { fetcherOptions } = useSaraContext();
  return reactQuery.useMutation<LogoutResponse, LogoutError, LogoutVariables>({
    mutationFn: (variables: LogoutVariables) =>
      fetchLogout(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type RefreshTokenError = Fetcher.ErrorWrapper<undefined>;

export type RefreshTokenVariables = {
  body: Schemas.RefreshTokenRequest;
} & SaraContext["fetcherOptions"];

/**
 * Get a new access token using a refresh token
 */
export const fetchRefreshToken = (
  variables: RefreshTokenVariables,
  signal?: AbortSignal
) =>
  saraFetch<
    Schemas.RefreshTokenResponse,
    RefreshTokenError,
    Schemas.RefreshTokenRequest,
    {},
    {},
    {}
  >({ url: "/auth/refresh", method: "post", ...variables, signal });

/**
 * Get a new access token using a refresh token
 */
export const useRefreshToken = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.RefreshTokenResponse,
      RefreshTokenError,
      RefreshTokenVariables
    >,
    "mutationFn"
  >
) => {
  const { fetcherOptions } = useSaraContext();
  return reactQuery.useMutation<
    Schemas.RefreshTokenResponse,
    RefreshTokenError,
    RefreshTokenVariables
  >({
    mutationFn: (variables: RefreshTokenVariables) =>
      fetchRefreshToken(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type RegisterError = Fetcher.ErrorWrapper<undefined>;

export type RegisterVariables = {
  body: Schemas.RegisterRequest;
} & SaraContext["fetcherOptions"];

/**
 * Register a new user account
 */
export const fetchRegister = (
  variables: RegisterVariables,
  signal?: AbortSignal
) =>
  saraFetch<
    Schemas.RegisterResponse,
    RegisterError,
    Schemas.RegisterRequest,
    {},
    {},
    {}
  >({ url: "/auth/register", method: "post", ...variables, signal });

/**
 * Register a new user account
 */
export const useRegister = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.RegisterResponse,
      RegisterError,
      RegisterVariables
    >,
    "mutationFn"
  >
) => {
  const { fetcherOptions } = useSaraContext();
  return reactQuery.useMutation<
    Schemas.RegisterResponse,
    RegisterError,
    RegisterVariables
  >({
    mutationFn: (variables: RegisterVariables) =>
      fetchRegister(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type ChatError = Fetcher.ErrorWrapper<undefined>;

export type ChatVariables = {
  body: Schemas.ChatRequest;
} & SaraContext["fetcherOptions"];

/**
 * Process chat request with OpenAI GPT 4 Omni model with web search capability
 */
export const fetchChat = (variables: ChatVariables, signal?: AbortSignal) =>
  saraFetch<Schemas.ChatResponse, ChatError, Schemas.ChatRequest, {}, {}, {}>({
    url: "/chat",
    method: "post",
    ...variables,
    signal,
  });

/**
 * Process chat request with OpenAI GPT 4 Omni model with web search capability
 */
export const useChat = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.ChatResponse,
      ChatError,
      ChatVariables
    >,
    "mutationFn"
  >
) => {
  const { fetcherOptions } = useSaraContext();
  return reactQuery.useMutation<Schemas.ChatResponse, ChatError, ChatVariables>(
    {
      mutationFn: (variables: ChatVariables) =>
        fetchChat(deepMerge(fetcherOptions, variables)),
      ...options,
    }
  );
};

export type GetChatHistoryQueryParams = {
  /**
   * External user ID to get chat history for
   */
  userId: string;
  /**
   * Optional topic ID to get history for a specific conversation
   */
  topicId?: string;
};

export type GetChatHistoryError = Fetcher.ErrorWrapper<undefined>;

export type GetChatHistoryVariables = {
  queryParams: GetChatHistoryQueryParams;
} & SaraContext["fetcherOptions"];

/**
 * Retrieve chat history for a user, either for all topics or for a specific topic
 */
export const fetchGetChatHistory = (
  variables: GetChatHistoryVariables,
  signal?: AbortSignal
) =>
  saraFetch<
    | Schemas.ChatHistorySingleTopicResponse
    | Schemas.ChatHistoryAllTopicsResponse,
    GetChatHistoryError,
    undefined,
    {},
    GetChatHistoryQueryParams,
    {}
  >({ url: "/chat-history", method: "get", ...variables, signal });

/**
 * Retrieve chat history for a user, either for all topics or for a specific topic
 */
export function getChatHistoryQuery(variables: GetChatHistoryVariables): {
  queryKey: reactQuery.QueryKey;
  queryFn: (
    options: QueryFnOptions
  ) => Promise<
    | Schemas.ChatHistorySingleTopicResponse
    | Schemas.ChatHistoryAllTopicsResponse
  >;
};

export function getChatHistoryQuery(
  variables: GetChatHistoryVariables | reactQuery.SkipToken
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((
        options: QueryFnOptions
      ) => Promise<
        | Schemas.ChatHistorySingleTopicResponse
        | Schemas.ChatHistoryAllTopicsResponse
      >)
    | reactQuery.SkipToken;
};

export function getChatHistoryQuery(
  variables: GetChatHistoryVariables | reactQuery.SkipToken
) {
  return {
    queryKey: queryKeyFn({
      path: "/chat-history",
      operationId: "getChatHistory",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchGetChatHistory(variables, signal),
  };
}

/**
 * Retrieve chat history for a user, either for all topics or for a specific topic
 */
export const useSuspenseGetChatHistory = <
  TData =
    | Schemas.ChatHistorySingleTopicResponse
    | Schemas.ChatHistoryAllTopicsResponse,
>(
  variables: GetChatHistoryVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      | Schemas.ChatHistorySingleTopicResponse
      | Schemas.ChatHistoryAllTopicsResponse,
      GetChatHistoryError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >
) => {
  const { queryOptions, fetcherOptions } = useSaraContext(options);
  return reactQuery.useSuspenseQuery<
    | Schemas.ChatHistorySingleTopicResponse
    | Schemas.ChatHistoryAllTopicsResponse,
    GetChatHistoryError,
    TData
  >({
    ...getChatHistoryQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

/**
 * Retrieve chat history for a user, either for all topics or for a specific topic
 */
export const useGetChatHistory = <
  TData =
    | Schemas.ChatHistorySingleTopicResponse
    | Schemas.ChatHistoryAllTopicsResponse,
>(
  variables: GetChatHistoryVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      | Schemas.ChatHistorySingleTopicResponse
      | Schemas.ChatHistoryAllTopicsResponse,
      GetChatHistoryError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >
) => {
  const { queryOptions, fetcherOptions } = useSaraContext(options);
  return reactQuery.useQuery<
    | Schemas.ChatHistorySingleTopicResponse
    | Schemas.ChatHistoryAllTopicsResponse,
    GetChatHistoryError,
    TData
  >({
    ...getChatHistoryQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables)
    ),
    ...options,
    ...queryOptions,
  });
};

export type SearchChatHistoryQueryParams = {
  /**
   * Search query
   */
  query: string;
  /**
   * Maximum number of results to return
   *
   * @default 10
   */
  limit?: number;
};

export type SearchChatHistoryError = Fetcher.ErrorWrapper<undefined>;

export type SearchChatHistoryVariables = {
  queryParams: SearchChatHistoryQueryParams;
} & SaraContext["fetcherOptions"];

/**
 * Search in chat history for the currently authenticated user
 */
export const fetchSearchChatHistory = (
  variables: SearchChatHistoryVariables,
  signal?: AbortSignal
) =>
  saraFetch<
    Schemas.SearchChatResponse,
    SearchChatHistoryError,
    undefined,
    {},
    SearchChatHistoryQueryParams,
    {}
  >({ url: "/search-chat", method: "get", ...variables, signal });

/**
 * Search in chat history for the currently authenticated user
 */
export function searchChatHistoryQuery(variables: SearchChatHistoryVariables): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.SearchChatResponse>;
};

export function searchChatHistoryQuery(
  variables: SearchChatHistoryVariables | reactQuery.SkipToken
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.SearchChatResponse>)
    | reactQuery.SkipToken;
};

export function searchChatHistoryQuery(
  variables: SearchChatHistoryVariables | reactQuery.SkipToken
) {
  return {
    queryKey: queryKeyFn({
      path: "/search-chat",
      operationId: "searchChatHistory",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchSearchChatHistory(variables, signal),
  };
}

/**
 * Search in chat history for the currently authenticated user
 */
export const useSuspenseSearchChatHistory = <
  TData = Schemas.SearchChatResponse,
>(
  variables: SearchChatHistoryVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.SearchChatResponse,
      SearchChatHistoryError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >
) => {
  const { queryOptions, fetcherOptions } = useSaraContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.SearchChatResponse,
    SearchChatHistoryError,
    TData
  >({
    ...searchChatHistoryQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

/**
 * Search in chat history for the currently authenticated user
 */
export const useSearchChatHistory = <TData = Schemas.SearchChatResponse>(
  variables: SearchChatHistoryVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.SearchChatResponse,
      SearchChatHistoryError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >
) => {
  const { queryOptions, fetcherOptions } = useSaraContext(options);
  return reactQuery.useQuery<
    Schemas.SearchChatResponse,
    SearchChatHistoryError,
    TData
  >({
    ...searchChatHistoryQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables)
    ),
    ...options,
    ...queryOptions,
  });
};

export type GetUserProfileError = Fetcher.ErrorWrapper<undefined>;

export type GetUserProfileVariables = SaraContext["fetcherOptions"];

/**
 * Get profile data for the currently logged-in user
 */
export const fetchGetUserProfile = (
  variables: GetUserProfileVariables,
  signal?: AbortSignal
) =>
  saraFetch<
    Schemas.UserProfileResponse,
    GetUserProfileError,
    undefined,
    {},
    {},
    {}
  >({ url: "/profile", method: "get", ...variables, signal });

/**
 * Get profile data for the currently logged-in user
 */
export function getUserProfileQuery(variables: GetUserProfileVariables): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.UserProfileResponse>;
};

export function getUserProfileQuery(
  variables: GetUserProfileVariables | reactQuery.SkipToken
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.UserProfileResponse>)
    | reactQuery.SkipToken;
};

export function getUserProfileQuery(
  variables: GetUserProfileVariables | reactQuery.SkipToken
) {
  return {
    queryKey: queryKeyFn({
      path: "/profile",
      operationId: "getUserProfile",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchGetUserProfile(variables, signal),
  };
}

/**
 * Get profile data for the currently logged-in user
 */
export const useSuspenseGetUserProfile = <TData = Schemas.UserProfileResponse>(
  variables: GetUserProfileVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.UserProfileResponse,
      GetUserProfileError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >
) => {
  const { queryOptions, fetcherOptions } = useSaraContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.UserProfileResponse,
    GetUserProfileError,
    TData
  >({
    ...getUserProfileQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

/**
 * Get profile data for the currently logged-in user
 */
export const useGetUserProfile = <TData = Schemas.UserProfileResponse>(
  variables: GetUserProfileVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.UserProfileResponse,
      GetUserProfileError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >
) => {
  const { queryOptions, fetcherOptions } = useSaraContext(options);
  return reactQuery.useQuery<
    Schemas.UserProfileResponse,
    GetUserProfileError,
    TData
  >({
    ...getUserProfileQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables)
    ),
    ...options,
    ...queryOptions,
  });
};

export type QueryOperation =
  | {
      path: "/conversations";
      operationId: "getUserConversations";
      variables: GetUserConversationsVariables | reactQuery.SkipToken;
    }
  | {
      path: "/";
      operationId: "getRoot";
      variables: GetRootVariables | reactQuery.SkipToken;
    }
  | {
      path: "/chat-history";
      operationId: "getChatHistory";
      variables: GetChatHistoryVariables | reactQuery.SkipToken;
    }
  | {
      path: "/search-chat";
      operationId: "searchChatHistory";
      variables: SearchChatHistoryVariables | reactQuery.SkipToken;
    }
  | {
      path: "/profile";
      operationId: "getUserProfile";
      variables: GetUserProfileVariables | reactQuery.SkipToken;
    };
