/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
/**
 * Response schema for property listing description generator
 */
export type PropertyListingResponse = {
  /**
   * Catchy title for the property listing
   */
  title: string;
  /**
   * Detailed description of the property
   */
  description: string;
  /**
   * List of key features or highlights of the property
   */
  key_features: string[];
  /**
   * Basic details about the property
   */
  property_details: {
    /**
     * Property address
     */
    address: string;
    /**
     * Number of bedrooms
     */
    beds?: void;
    /**
     * Number of bathrooms
     */
    baths?: void;
    /**
     * Type of property (apartment, house, condo, etc.)
     */
    property_type: string;
    /**
     * Listing price of the property (optional)
     */
    price?: void;
    /**
     * Square footage of the property (optional)
     */
    square_footage?: void;
  };
  /**
   * Details about how the listing was generated
   */
  analysis_details: {
    /**
     * Style of the listing description (professional, casual, luxury, etc.)
     */
    style_used?: string;
    /**
     * Whether key highlights were included
     */
    included_highlights?: boolean;
    /**
     * Whether neighborhood details were included
     */
    included_neighborhood?: boolean;
    /**
     * Number of images analyzed
     */
    images_analyzed?: number;
  };
};

export type PointOfInterest = {
  /**
   * Name of the point of interest
   */
  name?: string;
  /**
   * Address of the point of interest
   */
  address?: string;
  /**
   * Category of the point of interest
   */
  category?: string;
  /**
   * Original category from API
   */
  original_category?: string;
  /**
   * Distance in kilometers from the center location
   */
  distance_km?: number;
  geometry?: {
    location?: {
      /**
       * Latitude coordinate
       */
      lat?: number;
      /**
       * Longitude coordinate
       */
      lng?: number;
    };
  };
  /**
   * User rating (if available)
   */
  rating?: number;
  /**
   * Number of user ratings
   */
  user_ratings_total?: number;
  /**
   * Google Places ID for the location
   */
  place_id?: string;
  /**
   * URL to the Google Maps place
   */
  place_url?: string;
  /**
   * URL to Google Maps marker location
   */
  map_marker_url?: string;
  /**
   * URL to the icon for this place type
   */
  icon_url?: string;
  /**
   * Website for the place (if available)
   */
  website?: string;
  /**
   * Phone number for the place (if available)
   */
  phone?: string;
  /**
   * Types of place from Google Places API
   */
  types?: string[];
  display_info?: {
    /**
     * Display title for the place
     */
    title?: string;
    /**
     * Display subtitle (usually address)
     */
    subtitle?: string;
    /**
     * Human-readable category label
     */
    category_label?: string;
    /**
     * Formatted rating text
     */
    rating_text?: string;
  };
  /**
   * Relevance score for matching preferences
   */
  match_score?: number;
};

export type LifestyleMapResult = {
  /**
   * Points of interest grouped by distance range
   */
  grouped_by_distance?: {
    /**
     * Places within walking distance (0-1.5km)
     */
    walking_distance?: PointOfInterest[];
    /**
     * Places within biking distance (1.5-5km)
     */
    biking_distance?: PointOfInterest[];
    /**
     * Places within a short drive (5-10km)
     */
    short_drive?: PointOfInterest[];
    /**
     * Places further away (10-20km)
     */
    further_away?: PointOfInterest[];
  };
  /**
   * Information about the central location
   */
  location?: {
    /**
     * Formatted address of the location
     */
    address?: string;
    /**
     * Latitude coordinate
     */
    lat?: number;
    /**
     * Longitude coordinate
     */
    lng?: number;
  };
  /**
   * URL to Google Maps view of the location
   */
  map_url?: string;
  /**
   * Points of interest grouped by category
   */
  points_of_interest?: {
    [key: string]: PointOfInterest[];
  };
  /**
   * Parameters used for the search
   */
  search_params?: Record<string, any>;
};

export type ExpenseCategory = {
  /**
   * Name of the expense category
   */
  name?: string;
  /**
   * Monthly amount for this category
   */
  amount?: number;
};

export type FamilyExpensesResult = {
  /**
   * Location for the expense data (address, city, or neighborhood)
   */
  location?: string;
  /**
   * Number of people in the family
   */
  family_size?: number;
  /**
   * Currency code for the expense amounts
   */
  currency?: string;
  /**
   * Detailed expense data
   */
  expense_data?: {
    /**
     * Location for the expense data
     */
    location?: string;
    /**
     * Number of people in the family
     */
    family_size?: number;
    /**
     * Currency code for amounts
     */
    currency?: string;
    /**
     * Total monthly expenses
     */
    total?: number;
    /**
     * List of expense categories
     */
    categories?: ExpenseCategory[];
    /**
     * Additional context and explanation of the expense data
     */
    notes?: string;
  };
};

export type WebSearchResult = {
  /**
   * Results from web search
   */
  search_results: {
    /**
     * Title of the search result
     */
    title: string;
    /**
     * URL of the search result
     */
    url: string;
    /**
     * Snippet of text from the search result
     */
    snippet: string;
  }[];
};

/**
 * @example {"message":"I've created a lifestyle map for Austin showing the points of interest you requested...","tool_calls":[{"id":"call_abc123","type":"function","function":{"name":"create_lifestyle_map","arguments":"{\"location\":\"Austin, TX\",\"family_size\":4,\"categories\":[\"schools\",\"parks\",\"restaurants\"],\"preferences\":[\"family-friendly\"],\"radius\":2000}"}}],"tool_results":[{"tool_call_id":"call_abc123","function_name":"create_lifestyle_map","result":{"location":{"address":"Austin, TX, USA","lat":30.267153,"lng":-97.7430608},"points_of_interest":{"schools":[],"parks":[],"restaurants":[]},"distance_groups":{"walking_distance":[],"biking_distance":[],"short_drive":[],"further_away":[]},"map_url":"https://www.google.com/maps/..."}}],"map_description":"The Austin area offers a variety of amenities..."}
 */
export type ChatResponse = {
  /**
   * The assistant's response message
   */
  message: string;
  /**
   * List of tool calls made by the assistant
   */
  tool_calls?: {
    /**
     * Unique identifier for the tool call
     */
    id: string;
    /**
     * Type of tool call, currently only 'function' is supported
     */
    type: "function";
    ["function"]: {
      /**
       * Name of the function to call
       */
      name: string;
      /**
       * JSON string of arguments for the function
       */
      arguments: string;
    };
  }[];
  /**
   * Results of the tool calls
   */
  tool_results?: {
    /**
     * ID of the tool call this result is for
     */
    tool_call_id: string;
    /**
     * Name of the function that was called
     */
    function_name: string;
    /**
     * Result object returned by the function with data specific to the function that was called
     */
    result: Record<string, any>;
  }[];
  /**
   * Description of a map (if lifestyle map was requested)
   */
  map_description?: string;
  /**
   * Filtered map data (if provided)
   */
  filtered_map_data?: {
    [key: string]: any;
  };
  /**
   * Results from web search
   */
  web_search_results?: {
    /**
     * Title of the search result
     */
    title: string;
    /**
     * URL of the search result
     */
    url: string;
    /**
     * Snippet of text from the search result
     */
    snippet: string;
  }[];
  /**
   * Error message if something went wrong
   */
  error?: string;
};

export type SearchChatResponse = {
  /**
   * The search query used
   */
  query?: string;
  /**
   * List of matching conversations or messages
   */
  matches?: {
    /**
     * Topic ID of the conversation
     */
    topic_id?: string;
    /**
     * Title of the conversation (if available)
     */
    title?: string;
    /**
     * Type of match: topic_or_title or content
     */
    match_type?: "topic_or_title" | "content";
    /**
     * ID of the message where content match was found (only for content matches)
     */
    message_id?: number;
    /**
     * Preview of the matched content (only for content matches)
     */
    preview?: string;
    /**
     * Creation timestamp
     *
     * @format date-time
     */
    created_at?: string;
    /**
     * Role of the message sender (only for content matches)
     */
    role?: "user" | "assistant" | "system" | "tool";
  }[];
};

export type UserProfileResponse = {
  user?: {
    /**
     * User ID
     */
    id?: string;
    /**
     * User email
     */
    email?: string;
    /**
     * User's full name
     */
    name?: string;
    /**
     * User role (admin, user, etc.)
     */
    role?: string;
    /**
     * Account creation timestamp
     *
     * @format date-time
     */
    created_at?: string;
    /**
     * Account last update timestamp
     *
     * @format date-time
     */
    updated_at?: string;
  };
  stats?: {
    /**
     * Number of properties owned by the user
     */
    property_count?: number;
    /**
     * Number of chat conversations for this user
     */
    conversation_count?: number;
  };
  /**
   * List of properties owned by the user
   */
  properties?: {
    /**
     * Property ID
     */
    id?: number;
    /**
     * Property address
     */
    address?: string;
    /**
     * Property city
     */
    city?: string;
    /**
     * Property state
     */
    state?: string;
    /**
     * Property ZIP code
     */
    zip_code?: string;
    /**
     * Property price
     */
    price?: number;
    /**
     * Number of bedrooms
     */
    beds?: number;
    /**
     * Number of bathrooms
     */
    baths?: number;
    /**
     * Square footage
     */
    sqft?: number;
    /**
     * Type of property
     */
    property_type?: string;
    /**
     * Year the property was built
     */
    year_built?: number;
  }[];
};

export type LoginRequest = {
  /**
   * User email
   *
   * @format email
   */
  email: string;
  /**
   * User password
   *
   * @format password
   */
  password: string;
};

export type LoginResponse = {
  success?: boolean;
  message?: string;
  user?: {
    id?: string;
    name?: string;
    email?: string;
    role?: string;
  };
  /**
   * JWT access token
   */
  token?: string;
  /**
   * JWT refresh token used to obtain new access tokens
   */
  refresh_token?: string;
  /**
   * Token expiration time in seconds
   */
  expires_in?: number;
};

export type RefreshTokenRequest = {
  /**
   * Refresh token obtained during login
   */
  refresh_token: string;
};

export type RefreshTokenResponse = {
  success?: boolean;
  message?: string;
  /**
   * New JWT access token
   */
  token?: string;
  /**
   * Token expiration time in seconds
   */
  expires_in?: number;
};

export type RegisterRequest = {
  /**
   * User's full name
   */
  name: string;
  /**
   * User email
   *
   * @format email
   */
  email: string;
  /**
   * User password (min 8 characters)
   *
   * @format password
   */
  password: string;
};

export type RegisterResponse = {
  success?: boolean;
  message?: string;
  user?: {
    id?: string;
    name?: string;
    email?: string;
    role?: string;
  };
  token?: string;
};

export type ChatRequest = {
  /**
   * External user ID to track conversation history
   */
  userId: string;
  /**
   * Conversation topic ID to organize messages
   */
  topicId: string;
  /**
   * User message content
   */
  message: string;
  /**
   * Optional title for the conversation
   */
  title?: string;
  /**
   * Optional single image to analyze as part of the message
   *
   * @format binary
   */
  image?: Blob;
  /**
   * Optional multiple images to analyze as part of the message (for property listings, etc.)
   */
  images?: Blob[];
};

export type ChatHistoryParams = {
  /**
   * External user ID to get chat history for
   */
  userId: string;
  /**
   * Optional topic ID to get history for a specific conversation
   */
  topicId?: string;
};

export type ChatHistorySingleTopicResponse = {
  /**
   * Conversation topic ID
   */
  topic_id?: string;
  /**
   * User ID
   */
  user_id?: string;
  /**
   * Creation timestamp
   *
   * @format date-time
   */
  created_at?: string;
  /**
   * Last update timestamp
   *
   * @format date-time
   */
  updated_at?: string;
  /**
   * List of messages in this conversation
   */
  messages?: {
    /**
     * Message role (user, assistant, system, tool)
     */
    role?: string;
    /**
     * Message content
     */
    content?: string;
    /**
     * Message sequence number
     */
    sequence?: number;
    /**
     * Message timestamp
     *
     * @format date-time
     */
    timestamp?: string;
    /**
     * Tool calls if any
     */
    tool_calls?: Record<string, any>;
    /**
     * Tool results if any
     */
    tool_results?: Record<string, any>;
  }[];
};

export type UserConversationsResponse = {
  /**
   * The ID of the authenticated user
   */
  user_id?: string;
  /**
   * Total number of conversations available
   */
  total_count?: number;
  /**
   * Maximum number of conversations returned in this response
   */
  limit?: number;
  /**
   * Number of conversations skipped for pagination
   */
  offset?: number;
  /**
   * List of conversations for the user
   */
  conversations?: {
    /**
     * Unique database ID of the conversation
     */
    id?: string;
    /**
     * Topic ID of the conversation
     */
    topic_id?: string;
    /**
     * Title of the conversation (derived from content if not set)
     */
    title?: string;
    /**
     * Number of messages in this conversation
     */
    message_count?: number;
    /**
     * Preview text from the first user message
     */
    preview?: string;
    /**
     * Creation timestamp
     *
     * @format date-time
     */
    created_at?: string;
    /**
     * Last update timestamp
     *
     * @format date-time
     */
    updated_at?: string;
  }[];
};

export type ChatHistoryAllTopicsResponse = {
  /**
   * User ID
   */
  user_id?: string;
  /**
   * List of conversation topics
   */
  topics?: {
    /**
     * Conversation topic ID
     */
    topic_id?: string;
    /**
     * Optional conversation title
     */
    title?: string;
    /**
     * Creation timestamp
     *
     * @format date-time
     */
    created_at?: string;
    /**
     * Last update timestamp
     *
     * @format date-time
     */
    updated_at?: string;
    /**
     * Number of messages in this conversation
     */
    message_count?: number;
    /**
     * Preview of the last message
     */
    last_message?: string;
  }[];
};

export type ChatHistoryRequest = {
  /**
   * External user ID
   */
  userId: string;
  /**
   * Conversation topic ID
   */
  topicId: string;
  /**
   * Message role (user, assistant, system, tool)
   */
  role: "user" | "assistant" | "system" | "tool";
  /**
   * Message content
   */
  content: string;
  /**
   * Optional JSON string of tool calls
   */
  tool_calls?: string;
  /**
   * Optional JSON string of tool results
   */
  tool_results?: string;
  /**
   * Optional JSON string of panel data for UI display
   */
  panel_data?: string;
};

export type SearchChatHistoryRequest = {
  /**
   * Search query
   */
  query: string;
  /**
   * Maximum number of results to return
   *
   * @default 10
   */
  limit?: number;
};
